### ISSUE TITLE
Issue with BN on 1.19.1

### ISSUE THREAD

**Issue by TheGam1ngWizard** [Steel-Dev/BetterNetherite-Rewrite#1]
16:35:05] [Server thread/INFO]: [BetterNetherite] Loading BetterNetheriteRewrite v1.1.9
[16:35:05] [Server thread/ERROR]: [org.bukkit.craftbukkit.v1_19_R1.CraftServer] This version of Minecraft is unsupported: 1.19.1 initializing BetterNetheriteRewrite v1.1.9 (Is it up to date?)
dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.19.1
	at dev.jorel.commandapi.CommandAPIVersionHandler.getNMS(CommandAPIVersionHandler.java:86) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:155) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:140) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPI.onLoad(CommandAPI.java:166) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at com.abraxas.betternetheriterewrite.BetterNetheriteRewrite.onLoad(BetterNetheriteRewrite.java:23) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:427) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:278) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
	
	[16:35:07] [Server thread/INFO]: [BetterNetherite] Enabling BetterNetheriteRewrite v1.1.9
[16:35:07] [Server thread/ERROR]: Error occurred while enabling BetterNetheriteRewrite v1.1.9 (Is it up to date?)
dev.jorel.commandapi.exceptions.UnsupportedVersionException: This version of Minecraft is unsupported: 1.19.1
	at dev.jorel.commandapi.CommandAPIVersionHandler.getNMS(CommandAPIVersionHandler.java:86) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.<init>(CommandAPIHandler.java:155) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPIHandler.getInstance(CommandAPIHandler.java:140) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at dev.jorel.commandapi.CommandAPI.onEnable(CommandAPI.java:198) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at com.abraxas.betternetheriterewrite.BetterNetheriteRewrite.onEnable(BetterNetheriteRewrite.java:29) ~[Better Netherite Rewrite-1.1.9.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
[16:35:07] [Server thread/INFO]: [BetterNetherite] Disabling BetterNetheriteRewrite v1.1.9
[16:35:07] [Server thread/INFO]: [BetterNetherite] Successfully disabled.

**Comment by Steel-Dev** [comment]
Happened because the version of command api I was using didn't support 1.19.1 (they just released a version that does - lemme know if this works)
download it [here](https://drive.google.com/file/d/1gmek2W216KK-QpPCRVirZoZjMq717SFq/view?usp=sharing).

if this works well, I will release it on spigot.

**Comment by TheGam1ngWizard** [comment]
Apologies, I didn't get pinged here on Github. I downloaded your 1.1.10 version, and got the following error.
---

[16:04:15 INFO]: [BetterNetherite] Enabling BetterNetheriteRewrite v1.1.10
[16:04:15 ERROR]: Error occurred while enabling BetterNetheriteRewrite v1.1.10 (Is it up to date?)
java.lang.NoClassDefFoundError: dev/jorel/commandapi/CommandAPI
        at com.abraxas.betternetheriterewrite.BetterNetheriteRewrite.onEnable(BetterNetheriteRewrite.java:29) ~[better-netherite-rewrite-1.1.10.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-94]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-94]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: dev.jorel.commandapi.CommandAPI
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 10 more
[16:04:15 INFO]: [BetterNetherite] Disabling BetterNetheriteRewrite v1.1.10
[16:04:15 INFO]: [BetterNetherite] Successfully disabled.


Was like 'hmm, I can potentially troubleshoot the lack of commandapi by adding the plugin'. Re-ran, and got this following metrics problem.
[16:06:22] [Server thread/INFO]: [BetterNetherite] Enabling BetterNetheriteRewrite v1.1.10
[16:06:22] [Server thread/INFO]: [BetterNetherite] §7Checking for updates...
[16:06:22] [Server thread/ERROR]: Error occurred while enabling BetterNetheriteRewrite v1.1.10 (Is it up to date?)
java.lang.NoClassDefFoundError: org/bstats/bukkit/Metrics
	at com.abraxas.betternetheriterewrite.BetterNetheriteRewrite.startMetrics(BetterNetheriteRewrite.java:49) ~[better-netherite-rewrite-1.1.10.jar:?]
	at com.abraxas.betternetheriterewrite.BetterNetheriteRewrite.onEnable(BetterNetheriteRewrite.java:38) ~[better-netherite-rewrite-1.1.10.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:542) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:563) ~[paper-1.19.1.jar:git-Paper-94]
	at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:477) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:279) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1124) ~[paper-1.19.1.jar:git-Paper-94]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:305) ~[paper-1.19.1.jar:git-Paper-94]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bstats.bukkit.Metrics
	at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:151) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:103) ~[paper-api-1.19.1-R0.1-SNAPSHOT.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	... 11 more
[16:06:22] [Server thread/INFO]: [BetterNetherite] Disabling BetterNetheriteRewrite v1.1.10
[16:06:22] [Server thread/INFO]: [BetterNetherite] Successfully disabled.


I found this odd, so I looked to see if other plugins also had bstat issues, and they didn't ( example16:06:33] [Server thread/INFO]: [MythicMobs] Started up bStats Metrics[0m )

**Comment by Steel-Dev** [comment]
I accidentally gave you the non-shaded version of the plugin, which means it didn't contain CAPI and BStats - thus causing the error.
I've corrected the issue, you can try it [here](https://drive.google.com/file/d/1ScqRlkoEV1ujby6GQvSeMHQokgoA-gGE/view?usp=sharing).

**Comment by TheGam1ngWizard** [comment]
It does seem to have worked! If you get it up on the newest 1.19.2 patch I think your all good to push to Spigot!
